const FileActionTypes = {
  UPDATE_FILES_BY_KEY: "UPDATE_FILES_BY_KEY",
  SET_SELECTED_FILES: "SET_SELECTED_FILES",
  SET_CURRENT_PATH: "SET_CURRENT_PATH",
  POP_CURRENT_PATH: "POP_CURRENT_PATH",
  REFRESH_FILES: "REFRESH_FILES"
};

export default FileActionTypes;
